import unittest
from Queue import Queue

class QueueTets(unittest.TestCase):

    def test(self):
        Q = Queue()
        Q.enqueue(0)
        self.assertEqual(Q.que, [0, None, None, None, None, None])
        self.assertEqual(Q.head, 0)
        self.assertEqual(Q.tail, 1)
        Q.enqueue(1)
        self.assertEqual(Q.que, [0, 1, None, None, None, None])
        self.assertEqual(Q.head, 0)
        self.assertEqual(Q.tail, 2)
        Q.enqueue(2)
        self.assertEqual(Q.que, [0, 1, 2, None, None, None])
        self.assertEqual(Q.head, 0)
        self.assertEqual(Q.tail, 3)
        Q.enqueue(3)
        self.assertEqual(Q.que, [0, 1, 2, 3, None, None])
        self.assertEqual(Q.head, 0)
        self.assertEqual(Q.tail, 4)
        Q.enqueue(4)
        self.assertEqual(Q.que, [0, 1, 2, 3, 4, None])
        self.assertEqual(Q.head, 0)
        self.assertEqual(Q.tail, 5)
        Q.enqueue(5)
        self.assertEqual(Q.que, [0, 1, 2, 3, 4, None])
        self.assertEqual(Q.head, 0)
        self.assertEqual(Q.tail, 5)
        v = Q.dequeue()
        self.assertEqual(Q.que, [None, 1, 2, 3, 4, None])
        self.assertEqual(Q.head, 1)
        self.assertEqual(Q.tail, 5)
        self.assertEqual(v, 0)
        v = Q.dequeue()
        self.assertEqual(Q.que, [None, None, 2, 3, 4, None])
        self.assertEqual(Q.head, 2)
        self.assertEqual(Q.tail, 5)
        self.assertEqual(v, 1)
        Q.enqueue(99)
        self.assertEqual(Q.que, [None, None, 2, 3, 4, 99])
        self.assertEqual(Q.head, 2)
        self.assertEqual(Q.tail, 0)
        v = Q.dequeue()
        self.assertEqual(Q.que, [None, None, None, 3, 4, 99])
        self.assertEqual(Q.head, 3)
        self.assertEqual(Q.tail, 0)
        self.assertEqual(v, 2)
        v = Q.dequeue()
        self.assertEqual(Q.que, [None, None, None, None, 4, 99])
        self.assertEqual(Q.head, 4)
        self.assertEqual(Q.tail, 0)
        self.assertEqual(v, 3)
        v = Q.dequeue()
        self.assertEqual(Q.que, [None, None, None, None, None, 99])
        self.assertEqual(Q.head, 5)
        self.assertEqual(Q.tail, 0)
        self.assertEqual(v, 4)
        v = Q.dequeue()
        self.assertEqual(Q.que, [None, None, None, None, None, None])
        self.assertEqual(Q.head, 0)
        self.assertEqual(Q.tail, 0)
        self.assertEqual(v, 99)
        v = Q.dequeue()
        self.assertEqual(Q.que, [None, None, None, None, None, None])
        self.assertEqual(Q.head, 0)
        self.assertEqual(Q.tail, 0)
        self.assertEqual(v, None)


        


if __name__ == '__main__':
    unittest.main()